export { default as Navbar } from './navbar/Navbar'
export { default as Footer } from './footer/Footer'
export { default as MobileMenu } from './mobileMenu/MobileMenu'
export { default as CheckoutModel } from './checkoutModal/CheckoutModal'
export { default  as ECart } from './cart/ECart'
export { default as Categories } from './categories/Categories'
export { default as BestGear } from './bestgear/BestGear'